# 数据库配置项，相当于.ini文件
mysql:
  host: 127.0.0.1
  port: 3306
  db: chinatown_db
  user: root
  password: Abyss2260
  log-level: dev          # 日志等级 debug输出全部sql，dev，release线上环境
logger:
  level: info 
  prefix: '[chinatown]'
  director: log
  show-line: true         # 是否显示行号
  log-in-console: true    # 是否显示打印路径
system:
  host: 127.0.0.1
  port: 8080
  env: release #dev